# =============================================================================
# Sensor Configuration File - Version 1.0
#
# ➤ Units:
#     - Translation is in **meters**
#     - Rotation is in **degrees**, following the **right-hand rule**
#
# ➤ Reference Frame:
#     - All translations are relative to the **center of the IMU container**
#     - All measurements follow a **right-hand coordinate system**
#
# ➤ Sensor Location Codes (from back view):
#     - 0: Right side of the ATIS
#     - 1: Left side of the ATIS
#     - 2: Center
#
# ➤ Axis Remap:
#     - axis: 0 = x, 1 = y, 2 = z
#     - sign: +1 or -1
#     - Maps sensor axes relative to the parent coordinate system
# =============================================================================

version: 1.0
sensors:
  ins:
    sensor1:
      name: "INS_PORT" # placeholder for proprietary device/port
      parent_frame: "ins_acc_mass_center"
      sensor_location: 2
      engineer_notes: "Mounted inside ATIS, centered. Measurements are approximated."
      translation:
        x: 0.0 # redacted/placeholder
        y: 0.0 # redacted/placeholder
        z: 0.0 # redacted/placeholder
      angular:
        roll: 0.0 # redacted/placeholder
        pitch: 0.0 # redacted/placeholder
        yaw: 0.0 # redacted/placeholder
      axis_remap:
        x_sensor:
          axis: 1
          sign: -1
        y_sensor:
          axis: 0
          sign: 1
        z_sensor:
          axis: 2
          sign: 1
  lidar:
    sensor1:
      name: "LIDAR_PORT_1" # placeholder for proprietary IP/port
      parent_frame: "ins_acc_mass_center"
      sensor_location: 1
      engineer_notes: "Mounted on left side. Tilted downward. Measurements are approximated."
      translation:
        x: 0.0 # redacted/placeholder
        y: 0.0 # redacted/placeholder
        z: 0.0 # redacted/placeholder
      angular:
        roll: 0.0 # redacted/placeholder
        pitch: 0.0 # redacted/placeholder
        yaw: 0.0 # redacted/placeholder
      axis_remap:
        x_sensor:
          axis: 1
          sign: 1
        y_sensor:
          axis: 0
          sign: 1
        z_sensor:
          axis: 2
          sign: 1
    sensor2:
      name: "LIDAR_PORT_2" # placeholder for proprietary IP/port
      parent_frame: "ins_acc_mass_center"
      sensor_location: 0
      engineer_notes: "Mounted on right side. Tilted back. Measurements are approximated."
      translation:
        x: 0.0 # redacted/placeholder
        y: 0.0 # redacted/placeholder
        z: 0.0 # redacted/placeholder
      angular:
        roll: 0.0 # redacted/placeholder
        pitch: 0.0 # redacted/placeholder
        yaw: 0.0 # redacted/placeholder
      axis_remap:
        x_sensor:
          axis: 1
          sign: 1
        y_sensor:
          axis: 0
          sign: 1
        z_sensor:
          axis: 2
          sign: 1
  camera:
    sensor1:
      name: "CAMERA_PORT_1" # placeholder for proprietary IP
      parent_frame: "ins_box_center"
      sensor_location: 1
      engineer_notes: "Not Measured yet."
      translation:
        x: 0.0 # redacted/placeholder
        y: 0.0 # redacted/placeholder
        z: 0.0 # redacted/placeholder
      angular:
        roll: 0.0 # redacted/placeholder
        pitch: 0.0 # redacted/placeholder
        yaw: 0.0 # redacted/placeholder
      axis_remap:
        x_sensor:
          axis: 0
          sign: 1
        y_sensor:
          axis: 1
          sign: 1
        z_sensor:
          axis: 2
          sign: 1
    sensor2:
      name: "CAMERA_PORT_2" # placeholder for proprietary IP
      parent_frame: "ins_box_center"
      sensor_location: 1
      engineer_notes: "Not Measured yet."
      translation:
        x: 0.0 # redacted/placeholder
        y: 0.0 # redacted/placeholder
        z: 0.0 # redacted/placeholder
      angular:
        roll: 0.0 # redacted/placeholder
        pitch: 0.0 # redacted/placeholder
        yaw: 0.0 # redacted/placeholder
      axis_remap:
        x_sensor:
          axis: 0
          sign: 1
        y_sensor:
          axis: 1
          sign: 1
        z_sensor:
          axis: 2
          sign: 1
